Add build and host profiles
conan-io/cmake-conan pull request #250
Opened 2020-06-16 10:36 UTC by christophschlosser

Add option to make conan detection silent since it's triggered
three times otherwise when build and host profiles are specified.

2020-06-16 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/cmake-conan?pullRequest=250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/cmake-conan?pullRequest=250) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/cmake-conan?pullRequest=250) it.</sub>

2020-08-25 15:15 UTC, a4z commented
what is the status of this PR? 
nothing happens since more than 1 month. is there an other solution for using the new 2 profiles way, or something missing?

2020-08-28 16:10 UTC, czoido commented
Hi @christophschlosser thanks a lot for the contribution
Adding this to the milestone of the next release

cc @a4z

2020-09-01 08:28 UTC, danimtb approved these changes

2020-09-01 12:49 UTC, jgsogo requested changes
IMHO, I would say that the `--profile:host` (or `--profile`, it is the same) should take the value from any of the existing profile variables: `DEBUG_PROFILE`, `RELEASE_PROFILE`, `RELWITHDEBINFO_PROFILE`, `MINSIZEREL_PROFILE` or `PROFILE` like it is doing right now, and we should **add only the new `BUILD_PROFILE` variable** (not sure if `PROFILE_BUILD` would be a better name).

2020-09-07 07:54 UTC, czoido commented on conan.cmake
> +                     INSTALL_ARGS CONFIGURATION_TYPES BUILD_PROFILE HOST_PROFILE)
```suggestion
                     INSTALL_ARGS CONFIGURATION_TYPES PROFILE_BUILD)
```

2020-09-07 07:55 UTC, czoido commented
Hi @cschlosser,
I have added some suggestions as I can't push to your branch. Could you please check when possible?

2020-09-07 12:34 UTC, jgsogo approved these changes

2020-09-07 13:13 UTC, merged