Fix _get_msvc_ide_version for VS17.10
conan-io/cmake-conan pull request #643
Opened 2024-05-22 11:19 UTC by chrarnoldus

Visual Studio 17.10 was just released with MSVC version 1940, which gives an error: "Unknown MSVC compiler version"

https://learn.microsoft.com/sl-si/cpp/overview/compiler-versions?view=msvc-170

2024-05-22 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/conan-io/cmake-conan?pullRequest=643) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/conan-io/cmake-conan?pullRequest=643) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/conan-io/cmake-conan?pullRequest=643) it.</sub>

2024-05-23 16:02 UTC, puetzk requested changes

2024-05-23 16:02 UTC, puetzk commented on conan.cmake
> +    elseif(NOT MSVC_VERSION VERSION_LESS 1930 AND MSVC_VERSION VERSION_LESS 1941)
You should raise this all the way to 1950

Per https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/ the Visual Studio 17 v143 toolset is going to continue on through 14.4x.

> We will make separate announcements about MSVC compiler toolset versions beyond 14.4x (i.e., versions >= 14.50) at an appropriate time in the future.

2024-05-23 23:10 UTC, puetzk approved these changes
I'm not a maintainer (so this doesn't count to merge) but LGTM - it's now the same change I was going to propose...

2024-05-27 08:47 UTC, memsharded commented
I am going to merge this, even if the CI is not passing. This cmake-conan integration for Conan 1 is no longer maintained, and CI has been updated for Conan 2.

2024-05-27 08:47 UTC, merged